controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    interpolate_from_desired_state: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - link3_to_gripper_link
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    interpolate_from_desired_state: true
    allow_integration_in_goal_trajectories: true

joint_state_broadcaster:
  ros__parameters:
    # Publish to /roarm/joint_states instead of /joint_states
    # so it doesn't conflict with Leo Rover or other robots
    publish_joint_states_topic: /roarm/joint_states